# Generated by Django 6.0 on 2026-01-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Nouveau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='products',
        ),
        migrations.AddField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(related_name='promotions', to='Art_Nouveau.category', verbose_name='Categorii participante'),
        ),
        migrations.AddField(
            model_name='discount',
            name='email_subject',
            field=models.CharField(default='New sale!', max_length=200),
        ),
    ]
