# Generated by Django 5.2.7 on 2025-10-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Nouveau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='product',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='product',
        ),
        migrations.AddField(
            model_name='award',
            name='products',
            field=models.ManyToManyField(related_name='awards', to='Art_Nouveau.product'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='products',
            field=models.ManyToManyField(related_name='exhibitions', to='Art_Nouveau.product'),
        ),
    ]
