# Generated by Django 6.0 on 2026-01-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Nouveau', '0002_remove_discount_products_discount_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='active',
        ),
        migrations.AddField(
            model_name='discount',
            name='message_template',
            field=models.CharField(choices=[('Art_Nouveau/promo_formal.txt', 'Formal Promo Message'), ('Art_Nouveau/promo_urgent.txt', 'Urgent Promo Message')], default='Art_Nouveau/promo_formal.txt', max_length=100),
        ),
    ]
