# Generated by Django 6.0 on 2026-01-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Nouveau', '0003_remove_discount_active_discount_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False, help_text='If checked, the user cannot log in.'),
        ),
    ]
