# Generated by Django 5.2.7 on 2025-11-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Nouveau', '0003_product_image_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Ex: 'fas fa-paint-brush' sau 'fa fa-palette'", max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='auto generated if left empty', max_length=110, unique=True),
        ),
    ]
