# Generated by Django 5.2.7 on 2025-11-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Nouveau', '0004_category_icon_class_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
